In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
#name of the train folder
data_name = "game4"
image_width = 1920
image_height = 1080

train = pd.read_json("train/" + data_name + "/data/ball_markup.json")
train = train.transpose()

image_names = np.array([])

for e in train.transpose().loc[:,:]:
    # print(x, train.get(x)["x"])
    image_names = np.append(image_names, "frame" + str(e))


x_data = train.iloc[:,:].get("x")
y_data = train.iloc[:,:].get("y")

#remove the fractured indexes
x_data = np.full(x_data.size, x_data)
y_data = np.full(y_data.size, y_data)
image_names = np.full(image_names.size, image_names)


#take out the data with -1 coordinates i.e. when theres no ball
invalid_indicies = np.where(x_data == -1)

x_data_pruned = np.delete(x_data, invalid_indicies)
y_data_pruned = np.delete(y_data, invalid_indicies)
image_names_pruned = np.delete(image_names, invalid_indicies)


#create the coordinates based on the x and y data
data_size = x_data_pruned.size

x1_data = np.full(data_size, x_data_pruned - 7)
x2_data = np.full(data_size, x_data_pruned + 7)
y1_data = np.full(data_size, y_data_pruned - 7)
y2_data = np.full(data_size, y_data_pruned + 7)

#make arrays for the width and height columns
width = np.full(data_size, image_width)
height = np.full(data_size, image_height)


#make the data array

columns = ["image_id", "x1", "y1", "x2", "y2"]
data = np.array([image_names_pruned, x1_data, y1_data, x2_data, y2_data])
data = data.transpose()



data_frame = pd.DataFrame(data = data, columns=columns)



data_frame.to_csv("train/" + data_name + "/data/formatted_data.csv", index=False)


valid_idx = (train.iloc[:,:].index)
DF = pd.DataFrame(valid_idx)
DF.to_csv("train/" + data_name + "/data/valid_idx.csv", index=False)

data_frame

        image_id    x1   y1    x2   y2
0      frame1278  1370  518  1384  532
1      frame1298  1163  605  1177  619
2      frame1299  1151  610  1165  624
3      frame1300  1140  616  1154  630
4      frame1301  1130  623  1144  637
...          ...   ...  ...   ...  ...
6967  frame63007  1042  663  1056  677
6968  frame63008  1043  660  1057  674
6969  frame63009  1043  657  1057  671
6970  frame63010  1044  655  1058  669
6971  frame63011  1045  653  1059  667

[6972 rows x 5 columns]